[package]
name = "dhall_lua"
version = "0.1.0"
edition = "2021"

[lib]
name = "dhall_lua"
crate-type = ["cdylib"]

[features]
lua52 = ["mlua/lua52"]

[dependencies]
mlua = { version = "0.8", features = ["vendored", "module", "serialize"] }
serde = "1.0"
serde_dhall = "0.11.2"
